update cmd logic

diff --git a/harmonic/scripts/harmonic-install-scripts/user-data-runcmd.yaml b/harmonic/scripts/harmonic-install-scripts/user-data-runcmd.yaml
--- a/harmonic/scripts/harmonic-install-scripts/user-data-runcmd.yaml
+++ b/harmonic/scripts/harmonic-install-scripts/user-data-runcmd.yaml
@@ -9,17 +9,26 @@ disable_root: False
 preserve_hostname: False
 runcmd:
   - |
-    echo "=====================================================================================" \
-    && echo "Harmonic Installer: Setup" \
-    && echo "=====================================================================================" \
-    && echo "Harmonic Installer: Download 'harmonic-installer.sh' from Artifactory" \
-    && sudo wget https://artifactory.charterlab.com:443/artifactory/upload/harmonic/scripts/harmonic-installer.sh -O /opt/harmonic-installer.sh \
-    && sudo chmod +x /opt/harmonic-installer.sh \
-    && echo "=====================================================================================" \
-    && echo "Harmonic Installer: Running" \
-    && sudo /opt/harmonic-installer.sh -vip \
-    && echo "=====================================================================================" \
-    && echo "Harmonic Installer: Complete" \
-    && echo "=====================================================================================" \
-    && echo "Harmonic Installer: Rebooting System" \
-    && sudo systemctl --message="Harmonic Post-Install Reboot" reboot
+    echo "==================================================================="
+    echo "Harmonic Installer: Setup"
+    echo "==================================================================="
+    echo "Harmonic Installer: Update resolver"
+    echo "==================================================================="
+    cat < EOF >/etc/resolv.conf
+    echo "Harmonic Installer: Downloading 'harmonic-installer.sh'"
+    echo "==================================================================="
+    if (sudo wget https://artifactory.charterlab.com:443/artifactory/upload/harmonic/scripts/harmonic-installer.sh -O /opt/harmonic-installer.sh && sudo chmod +x /opt/harmonic-installer.sh); then
+      echo "Harmonic Installer: Running"
+      else
+      echo "Harmonic Installer: Failed to download 'harmonic-installer.sh'"
+      exit 1
+      fi
+    echo "==================================================================="
+    if (sudo /opt/harmonic-installer.sh -ip); then
+      echo "==================================================================="
+      echo "Harmonic Installer: Installation Complete"
+      else
+      echo "==================================================================="
+      echo "Harmonic Installer: Installation Failed"
+      exit 1
+      fi
